function h5type = matlab_to_h5type(dtype)
% Map MATLAB class name to an h5create-compatible type string.
    map = struct( ...
        'double',  'double', ...
        'single',  'single', ...
        'int8',    'int8',   ...
        'int16',   'int16',  ...
        'int32',   'int32',  ...
        'int64',   'int64',  ...
        'uint8',   'uint8',  ...
        'uint16',  'uint16', ...
        'uint32',  'uint32', ...
        'uint64',  'uint64'  ...
    );
    if isfield(map, dtype)
        h5type = map.(dtype);
    else
        h5type = 'double';
    end
end

